/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p1proyectogrupal1_metodologiadesarrollosoftware.RegistrarCuenta;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mycompany.p1proyectogrupal1_metodologiadesarrollosoftware.Repartidor.Panel_Repartidor;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.bson.Document;
import org.bson.conversions.Bson;

/**
 *
 * @author jenni
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        usuarioTxt.setOpaque(false);
        usuarioTxt.setBackground(new Color (0,0,0,0));
        contraseñaTxt.setOpaque(false);
        contraseñaTxt.setBackground(new Color (0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        usuarioTxt = new javax.swing.JTextField();
        contraseñaTxt = new javax.swing.JPasswordField();
        mostrarContraBtt = new javax.swing.JButton();
        iniciarSesionBtt = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioTxt.setBorder(null);
        getContentPane().add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 340, 40));

        contraseñaTxt.setBorder(null);
        getContentPane().add(contraseñaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 290, 40));

        mostrarContraBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarContraBttActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarContraBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 423, 50, 40));

        iniciarSesionBtt.setText("iniciar sesion");
        iniciarSesionBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBttActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarSesionBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 350, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicioSesion.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean mostrarContraseña = false;
    private void mostrarContraBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarContraBttActionPerformed

        mostrarContraseña = !mostrarContraseña;
        if (mostrarContraseña) {
            contraseñaTxt.setEchoChar((char) 0); 
        } else {
            contraseñaTxt.setEchoChar('*'); 
        }
    }//GEN-LAST:event_mostrarContraBttActionPerformed

    private void iniciarSesionBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBttActionPerformed
     String usuario = usuarioTxt.getText().trim();
        String contraseña = new String(contraseñaTxt.getPassword()).trim();

        if (usuario.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el usuario y la contraseña.");
            return;
        }

        String connectionString = "mongodb://localhost:27017";
        try (MongoClient mongoClient = MongoClients.create(connectionString)) {
            MongoDatabase database = mongoClient.getDatabase("Paqueteria");
            MongoCollection<Document> collection = database.getCollection("usuarios");

            Bson filter = Filters.and(Filters.eq("usuario", usuario), Filters.eq("contraseña", contraseña));
            Document usuarioDoc = collection.find(filter).first();

            if (usuarioDoc != null) {
                String rol = usuarioDoc.getString("rol");
                if ("Repartidor".equals(rol)) {
                    JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso. Redirigiendo a Panel Repartidor.");
                    Panel_Repartidor panelRepartidor = new Panel_Repartidor();
                    panelRepartidor.setVisible(true);
                    this.dispose(); // Cerrar la ventana de inicio de sesión
                } else {
                    JOptionPane.showMessageDialog(this, "Rol no autorizado para esta operación.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos.");
        }
    }//GEN-LAST:event_iniciarSesionBttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseñaTxt;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton iniciarSesionBtt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton mostrarContraBtt;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
