/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p1proyectogrupal1_metodologiadesarrollosoftware.Administrador;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Panel_Administrador extends javax.swing.JFrame {
    CalculatePrice cp=new CalculatePrice();
    RegistrarPaquete rp=new RegistrarPaquete();
    /**
     * Creates new form Panel_Administrador
     */
    public Panel_Administrador() {
        this.setUndecorated(true);
        
        initComponents();
        this.setLocationRelativeTo(null); 
        
        Tarifa.setEditable(false);
        cp.valor(DimentionsComboBox, Weight, PlaceCombo, Tarifa);
        
        BotonPanel.setContentAreaFilled(false); // No pinta el contenido del botón
        BotonPanel.setBorderPainted(false); // No pinta el borde del botón
        BotonPanel.setFocusPainted(false); // No pinta el enfoque del botón
        BotonPanel.setOpaque(false);
        
        BotonRastreo.setContentAreaFilled(false); 
        BotonRastreo.setBorderPainted(false); 
        BotonRastreo.setFocusPainted(false);
        BotonRastreo.setOpaque(false);
        
        BotonEnvio.setContentAreaFilled(false); 
        BotonEnvio.setBorderPainted(false); 
        BotonEnvio.setFocusPainted(false);
        BotonEnvio.setOpaque(false);
        
        BotonAdministrarCuenta.setContentAreaFilled(false); 
        BotonAdministrarCuenta.setBorderPainted(false); 
        BotonAdministrarCuenta.setFocusPainted(false);
        BotonAdministrarCuenta.setOpaque(false);
        
        BotonHistorial.setContentAreaFilled(false); 
        BotonHistorial.setBorderPainted(false); 
        BotonHistorial.setFocusPainted(false);
        BotonHistorial.setOpaque(false);
        
        BotonSalir.setContentAreaFilled(false); 
        BotonSalir.setBorderPainted(false); 
        BotonSalir.setFocusPainted(false);
        BotonSalir.setOpaque(false);
        
        BotonBodega.setContentAreaFilled(false); 
        BotonBodega.setBorderPainted(false); 
        BotonBodega.setFocusPainted(false);
        BotonBodega.setOpaque(false);
        
        Register.setContentAreaFilled(false); 
        Register.setBorderPainted(false); 
        Register.setFocusPainted(false);
        Register.setOpaque(false);
        
        //Visibilidad inicial de paneles
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonEnvio = new javax.swing.JButton();
        BotonRastreo = new javax.swing.JButton();
        BotonAdministrarCuenta = new javax.swing.JButton();
        BotonHistorial = new javax.swing.JButton();
        BotonBodega = new javax.swing.JButton();
        BotonPanel = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NameR = new javax.swing.JTextField();
        ID_R = new javax.swing.JTextField();
        CellR = new javax.swing.JTextField();
        NameD = new javax.swing.JTextField();
        ID_D = new javax.swing.JTextField();
        CellD = new javax.swing.JTextField();
        PlaceCombo = new javax.swing.JComboBox<>();
        Direction = new javax.swing.JTextField();
        Weight = new javax.swing.JTextField();
        DimentionsComboBox = new javax.swing.JComboBox<>();
        NameT = new javax.swing.JTextField();
        ID_T = new javax.swing.JTextField();
        PlacaT = new javax.swing.JTextField();
        Tarifa = new javax.swing.JTextField();
        Register = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnvioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 220, 30));

        BotonRastreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRastreoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRastreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 210, 30));

        BotonAdministrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAdministrarCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAdministrarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 210, 50));

        BotonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(BotonHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 210, 60));

        BotonBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBodegaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 190, 60));

        BotonPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPanelActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, 50));

        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 110, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Admin-Main.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(NameR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 190, 30));
        jPanel2.add(ID_R, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 190, 30));

        CellR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CellRActionPerformed(evt);
            }
        });
        jPanel2.add(CellR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 190, 30));
        jPanel2.add(NameD, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 190, 30));
        jPanel2.add(ID_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 190, 30));

        CellD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CellDActionPerformed(evt);
            }
        });
        jPanel2.add(CellD, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 190, 30));

        PlaceCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quito", "Guayaquil", "Cuenca", "Ibarra", "Manta", "Loja", "Ambato", "Riobamba", "Santo Domingo", "Quevedo" }));
        PlaceCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceComboActionPerformed(evt);
            }
        });
        jPanel2.add(PlaceCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 140, 30));
        jPanel2.add(Direction, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, 200, 30));

        Weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightActionPerformed(evt);
            }
        });
        jPanel2.add(Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 550, 200, 30));

        DimentionsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30x30x30", "50x50x50", "70x70x70", "90x90x90", "120x120x120" }));
        DimentionsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DimentionsComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(DimentionsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 200, 30));
        jPanel2.add(NameT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 700, 190, 30));

        ID_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_TActionPerformed(evt);
            }
        });
        jPanel2.add(ID_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 700, 170, 30));

        PlacaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaTActionPerformed(evt);
            }
        });
        jPanel2.add(PlacaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 692, 190, 30));

        Tarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarifaActionPerformed(evt);
            }
        });
        jPanel2.add(Tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 610, 50, 30));

        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel2.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Admin-Envio.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1280, 800));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Admin-Bodega.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Admin-Historial.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CellRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CellRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CellRActionPerformed

    private void CellDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CellDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CellDActionPerformed

    private void ID_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_TActionPerformed

    private void PlacaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaTActionPerformed

    private void BotonPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPanelActionPerformed
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BotonPanelActionPerformed

    private void BotonEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnvioActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BotonEnvioActionPerformed

    private void BotonBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBodegaActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BotonBodegaActionPerformed

    private void BotonRastreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRastreoActionPerformed
        /*jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(true);*/// TODO add your handling code here:
    }//GEN-LAST:event_BotonRastreoActionPerformed

    private void BotonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHistorialActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BotonHistorialActionPerformed

    private void BotonAdministrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAdministrarCuentaActionPerformed
        /*jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);*/// TODO add your handling code here:
    }//GEN-LAST:event_BotonAdministrarCuentaActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void TarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarifaActionPerformed
        ;// TODO add your handling code here:
    }//GEN-LAST:event_TarifaActionPerformed

    private void PlaceComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceComboActionPerformed
        cp.valor(DimentionsComboBox, Weight, PlaceCombo, Tarifa);// TODO add your handling code here:
    }//GEN-LAST:event_PlaceComboActionPerformed

    private void WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightActionPerformed
        try {
    String text = Weight.getText();
    if (!text.isEmpty()) {
        double number = Double.parseDouble(text);
        if (number <= 0) {
            // Si el número es menor o igual a cero, mostrar mensaje de error
            JOptionPane.showMessageDialog(this,
                    "Por favor, ingrese un número mayor a cero.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            Weight.setText("");
            return; // Salir del método si hay un error de validación
        }
    }
} catch (NumberFormatException ex) {
    // Si ocurre un error al parsear el número, mostrar mensaje de error
    JOptionPane.showMessageDialog(this,
            "Por favor, ingrese un número válido.",
            "Error", JOptionPane.ERROR_MESSAGE);
    Weight.setText("");
    return; // Salir del método si hay un error de validación
}

// Si la validación es exitosa, llamar a cp.valor()
cp.valor(DimentionsComboBox, Weight, PlaceCombo, Tarifa);// TODO add your handling code here:
    }//GEN-LAST:event_WeightActionPerformed

    private void DimentionsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DimentionsComboBoxActionPerformed
        cp.valor(DimentionsComboBox, Weight, PlaceCombo, Tarifa);// TODO add your handling code here:
    }//GEN-LAST:event_DimentionsComboBoxActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        if(NameR.getText().isEmpty()||ID_R.getText().isEmpty()||CellR.getText().isEmpty()||NameD.getText().isEmpty()||ID_D.getText().isEmpty()||CellD.getText().isEmpty()||Direction.getText().isEmpty()||Weight.getText().isEmpty()||NameT.getText().isEmpty()||ID_T.getText().isEmpty()||PlacaT.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Llene todos los campos");
         return;
        }
        if (!ID_R.getText().matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "La cédula del remitente debe tener 10 dígitos.");
        return;
        }
        if (!CellR.getText().matches("09\\d{8}")) {
        JOptionPane.showMessageDialog(this, "Los datos del celular del remitente son incorrectos."); 
        return;
        }
        if (!ID_D.getText().matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "La cédula del destinatario debe tener 10 dígitos.");
        return;
        }
        if (!CellD.getText().matches("09\\d{8}")) {
        JOptionPane.showMessageDialog(this, "Los datos del celular del destinatario son incorrectos."); 
        return;
        }
        if(!ID_T.getText().matches("[A-Z]\\d{4}")) {
        JOptionPane.showMessageDialog(this, "ID de transporte incorrecto, el formato es una letra mayuscula+4 numeros.");
        return;
        }
        if (!PlacaT.getText().matches("[A-Z]{3}-\\d{3}")) {
        JOptionPane.showMessageDialog(this, "Placa de transporte incorrecto, el formato es una 3 letras mayusculas+guion+3 numeros.");
        return;
        }
        rp.RegistroEnvio(NameR, ID_R, CellR, NameD, ID_D, CellD, PlaceCombo, Direction, DimentionsComboBox, Weight, Tarifa, NameT, ID_T, PlacaT);
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAdministrarCuenta;
    private javax.swing.JButton BotonBodega;
    private javax.swing.JButton BotonEnvio;
    private javax.swing.JButton BotonHistorial;
    private javax.swing.JButton BotonPanel;
    private javax.swing.JButton BotonRastreo;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextField CellD;
    private javax.swing.JTextField CellR;
    private javax.swing.JComboBox<String> DimentionsComboBox;
    private javax.swing.JTextField Direction;
    private javax.swing.JTextField ID_D;
    private javax.swing.JTextField ID_R;
    private javax.swing.JTextField ID_T;
    private javax.swing.JTextField NameD;
    private javax.swing.JTextField NameR;
    private javax.swing.JTextField NameT;
    private javax.swing.JTextField PlacaT;
    private javax.swing.JComboBox<String> PlaceCombo;
    private javax.swing.JButton Register;
    private javax.swing.JTextField Tarifa;
    private javax.swing.JTextField Weight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
